schema-version = 1

[package]
title = "Astra"
version = "0.1.0"
id = "com.astra.tv"

[components]
[[components.interactive]]
id = "com.astra.tv.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main"]
